[project]
name = "GoL"
version = "0.1"
dependencies = ["numpy", "matplotlib"]
requires-python = ">=3.9"

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"